name: Build apps CI

on:
  push:
    branches:
      - 'build/v**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/heads/build/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: npm run install:ci

      - run: npm run install:babel

      - run: npm run build:ci

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64.zip
          path: build/win/qqtools-${{ env.VERSION }}-win64.zip
