name: Build apps CI

on:
  push:
    branches:
      - 'build-node-oicqhttp/v**'

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/heads/build-node-oicqhttp/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: npm run install:ci

      - run: npm run install:babel

      - run: npm run build:ci

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          draft: true
          prerelease: true
          files: |
            build/node-oicqhttp/node-oicqhttp-${{ env.VERSION }}-linux64.zip
            build/node-oicqhttp/node-oicqhttp-${{ env.VERSION }}-macos.zip
            build/node-oicqhttp/node-oicqhttp-${{ env.VERSION }}-win.zip