name: gitee-sync

on:
  - push

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'https://github.com/duan602728596/qqtools.git'
          destination-repo: 'git@gitee.com:duanhaochen/qqtools.git'